---
# This playbook deploys the following services on the instances
# for the preparation on Python2.7.9 installation

- name: Update apt cache
  apt: 
    update_cache=yes 
    cache_valid_time=3600

- name: Make sure the required services are installed
  apt: 
    name={{ item }}
    state=present 
    force=yes
  with_items: 
    - build-essential
    - libreadline-gplv2-dev
    - libncursesw5-dev
    - libssl-dev
    - libsqlite3-dev
    - tk-dev
    - libgdbm-dev
    - libc6-dev
    - libbz2-dev
    - checkinstall
    - python-bsddb3
